### PR TITLE
Switch to Flowzone

### PR DESCRIPTION
**Pull request by ab77**
Change-type: patch

### CODE REVIEW

**Comment by ab77** [comment]
@builder555 if the repository doesn't need to have capital letters, perhaps consider renaming. See, https://github.com/balena-io-hardware/EtcherPro-Fleet/actions/runs/3228389421/jobs/5284465366#step:10:14

cc @klutchell

**Comment by klutchell** [comment]
> @builder555 if the repository doesn't need to have capital letters, perhaps consider renaming. See, https://github.com/balena-io-hardware/EtcherPro-Fleet/actions/runs/3228389421/jobs/5284465366#step:10:14
> 
> cc @klutchell

@ab77 we should have Flowzone convert the case to lower before making the API calls.

**Comment by ab77** [comment]
> > @builder555 if the repository doesn't need to have capital letters, perhaps consider renaming. See, https://github.com/balena-io-hardware/EtcherPro-Fleet/actions/runs/3228389421/jobs/5284465366#step:10:14
> > cc @klutchell
> 
> @ab77 we should have Flowzone convert the case to lower before making the API calls.

Yep, I arrived at the same conclusion a few minutes ago: https://github.com/product-os/flowzone/pull/257

**Comment by ab77** [comment]
@builder555 here's the draft release: https://dashboard.balena-cloud.com/fleets/1859867/releases/2331435

**Review by builder555 — APPROVED** [review]

**Pull request merged**
